### ISSUE TITLE
[Bug] Language

### ISSUE THREAD

**Issue by MonoAdrian23** [thebigsmileXD/MagicWE2#174] opened 2020-02-02 19:12 UTC
At First sorry for my bad english.
Language is Set to german but plugin language is already english.
Join Message is MagicWe2 Language was set to english.

MagicWe Latest 
Pocketmine 3.11.4

I hope you can help me please.
Thanks for this good Plugin!

**Comment by inxomnyaa** [comment] 2020-02-02 22:48
Duplicate of #173 , i hope that will clarify the issue for you ^^

**Closed as completed** 2020-02-02 22:48 UTC
Labels: Bug, Duplicate
