### ISSUE TITLE
[10.0.1] //copy failing to copy

### ISSUE THREAD

**Issue by dev-ste** [thebigsmileXD/MagicWE2#209] opened 2020-12-03 00:54 UTC
### Description

When I use //copy. It tells me to add flags. So I put "0" as my flag (that works for every other command) and it tells me "Looks like you are missing an argument or used the command wrong!"

---
| MagicWE2 v10.0.1 | Information |
| --- | --- |
| Website | https://github.com/thebigsmileXD/MagicWE2 |
| Version | 10.0.1 |
| Plugin API Version | 3.9, 3.10, 3.11 |
| Authors | XenialDan |
| Enabled | Yes |
| Uses UI | No |
| Phar | No |
| PMMP Protocol Version | v1.16.100 |
| PMMP Version | 3.16.0 |
| PMMP API Version | 3.16.0 |

**Comment by inxomnyaa** [comment] 2020-12-03 10:43
PM3 is not supported anymore

**Comment by inxomnyaa** [comment] 2020-12-03 10:45
Duplicate of https://github.com/thebigsmileXD/MagicWE2/issues/177

**Closed as completed by inxomnyaa** 2020-12-03 10:45 UTC
