### ISSUE TITLE
[Bug] //paste can't stand the change of world

### ISSUE THREAD

**Issue by UnEnanoMas** [thebigsmileXD/MagicWE2#196] opened 2020-08-21 17:35 UTC
I don't have a lot of time to spend in saying which version I use and all that, I am currently testing the latest dev of this plugin, I have everything updated, both pocketmine and Minecraft

The point is that when I use // copy it makes it perfect, but when you go to another world and try to paste it, it says that it has been pasted but nothing appears, but if you go to the world where you copied it and use the // paste command it works

It was just that

**Comment by inxomnyaa** [comment] 2020-08-24 14:14
Did not properly use issue template. Repetitive action will lead to ban. Closing as invalid

**Comment by inxomnyaa** [comment] 2020-08-24 14:15
If you got no time to properly create an issue, then i got no time to read it.

**Closed as completed by inxomnyaa** 2020-08-24 14:14 UTC
Labels: State: Fixed, Duplicate, Invalid

**Comment by UnEnanoMas** [comment] 2020-08-24 16:45
Oh sorry, poor thing, you can't read 3 lines.

Good luck with your bugin

**Comment by inxomnyaa** [comment] 2020-08-27 07:01
Oh sorry, poor thing, you can't write 3 lines (or use a single command `//bug` that auto-generates a bug report), bo-hooo

**Comment by inxomnyaa** [comment] 2020-08-27 07:15
Duplicate of #30 #185
