### ISSUE TITLE
[FR] //fix 

### ISSUE THREAD

**Issue by UnEnanoMas** [thebigsmileXD/MagicWE2#195] opened 2020-08-13 21:51 UTC
https://github.com/CzechPMDevs/BuilderTools/tree/41b127a689d523683f8cd3c5e3704688073a818f

**I would like the // fix command to be added because it is very useful when you import a Java map, it fixes all the blocks that are wrong**

**Comment by inxomnyaa** [comment] 2020-08-17 09:28
See #10
Duplicate of #118

**Closed as completed by inxomnyaa** 2020-08-17 09:28 UTC
Labels: Feature Request
